# Site settings
title: Landed
email: tkchen@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/touchinteraffective"
url: http://127.0.0.1:4000
twitter_username: uclatommy
github_username:  uclatommy

# Build settings
markdown: kramdown
