# site settings
title: Touch Interaffective
subtitle: games for all the senses
email: contact@phoenixperry.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address:
city: New York/London
state:
zip_code:
country: US/UK
phone: +1-718-312-1410

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: h
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:  

# build settings
markdown: kramdown

sass:
  style: compressed
